import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const outDir = resolve(root, 'src/mlb_studio/static');
await mkdir(outDir, { recursive: true });

const reactSource = (await readFile(resolve(here, 'vendor/react.production.min.js'), 'utf8')).trim();
const reactDomSource = (await readFile(resolve(here, 'vendor/react-dom.production.min.js'), 'utf8')).trim();
const runtimeSource = (await readFile(resolve(here, 'src/react-runtime.js'), 'utf8')).trim();
const legacySource = (await readFile(resolve(here, 'src/legacy-builder.js'), 'utf8')).trim();
const reactBootstrap = [
  '/* ---- React 16 production ---- */\n' + reactSource,
  '/* ---- ReactDOM 16 production ---- */\n' + reactDomSource,
  '/* ---- MLBricks React runtime islands ---- */\n' + runtimeSource,
].join('\n');

// Full Window serializes the current Studio factory into about:blank. Preserve
// the React bootstrap separately so the detached window receives the same React
// runtime islands instead of silently falling back to the old redraw path.
const bootstrapLiteral = JSON.stringify(reactBootstrap + '\n');
const js = [
  '/* MLBricks Studio compiled frontend. Generated by frontend/build.mjs. */',
  reactBootstrap,
  `window.__MLB_REACT_BOOTSTRAP_SOURCE__=${bootstrapLiteral};`,
  '/* ---- MLBricks legacy graph/editor shell ---- */',
  legacySource,
  ''
].join('\n');

await writeFile(resolve(outDir, 'builder.js'), js, 'utf8');
await writeFile(resolve(outDir, 'builder.css'), await readFile(resolve(here, 'src/builder.css')), 'utf8');
console.log(`Built ${resolve(outDir, 'builder.js')}`);
console.log(`Built ${resolve(outDir, 'builder.css')}`);
