[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlb-studio"
version = "1.0.0b2"
description = "Short PyPI alias for MLBricks Studio."
readme = "README.md"
requires-python = ">=3.10"
license = "PolyForm-Noncommercial-1.0.0"
license-files = ["LICENSE"]
authors = [
  { name = "Zameer Hussain" },
  { name = "Akhtar Hussain" }
]
dependencies = [
  "mlbricks-studio==1.0.0b2"
]

[project.optional-dependencies]
data = ["mlbricks-studio[data]==1.0.0b2"]
cloud = ["mlbricks-studio[cloud]==1.0.0b2"]
serve = ["mlbricks-studio[serve]==1.0.0b2"]

[project.urls]
Homepage = "https://github.com/MlBricks/MLBricks-Studio"
Repository = "https://github.com/MlBricks/MLBricks-Studio"

[tool.setuptools]
packages = []
